# Generated by Django 4.2.1 on 2023-07-05 13:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='cantidad_personas',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='extra',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
