# Generated by Django 4.2.1 on 2023-05-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='elaboracion',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/resources/img'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(max_length=2000),
        ),
    ]
