# Generated by Django 4.2.1 on 2023-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_alter_receta_elaboracion_alter_receta_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='admin-interface/img'),
        ),
    ]
