# Generated by Django 4.1.7 on 2023-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receta", "0004_receta_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receta",
            name="imagen",
            field=models.ImageField(blank=True, upload_to="recetas"),
        ),
    ]
