# Generated by Django 4.2.1 on 2023-05-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volanta', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('autor_a', models.CharField(max_length=200)),
                ('cuerpo', models.CharField(max_length=2000)),
                ('imagen', models.ImageField(null=True, upload_to='static/resources')),
                ('epigrafe', models.CharField(max_length=200)),
            ],
        ),
    ]
