# Generated by Django 4.2.1 on 2023-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_noticia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='epigrafe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
