# Generated by Django 4.1.7 on 2023-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticia", "0003_alter_noticia_epigrafe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="imagen",
            field=models.ImageField(blank=True, upload_to="noticias"),
        ),
    ]
