# Generated by Django 4.2.1 on 2023-06-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0003_alter_seccion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1200)),
                ('imagen', models.ImageField(blank=True, upload_to='media/img')),
            ],
            options={
                'verbose_name_plural': 'Historia',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1200)),
                ('imagen', models.ImageField(blank=True, upload_to='media/img')),
            ],
            options={
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1200)),
                ('imagen', models.ImageField(blank=True, upload_to='media/img')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name_plural': 'Secciones'},
        ),
    ]
