# Generated by Django 4.2.1 on 2023-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0004_historia_nosotros_servicios_alter_seccion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
        migrations.AddField(
            model_name='servicios',
            name='items',
            field=models.ManyToManyField(related_name='servicios', to='seccion.item'),
        ),
    ]
