# Generated by Django 4.2.1 on 2023-06-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0005_item_remove_servicios_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='items',
        ),
        migrations.AddField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
