# Generated by Django 4.2.1 on 2023-06-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0007_alter_servicios_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/img'),
        ),
    ]
