# Generated by Django 4.2.1 on 2023-06-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0008_alter_historia_imagen_alter_nosotros_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={},
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='imagen',
        ),
    ]
