# Generated by Django 4.2.1 on 2023-07-05 11:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0010_alter_historia_imagen_alter_nosotros_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
