# Generated by Django 4.2.1 on 2023-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0012_servicios_descripcion_servicios_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='vigencia',
            field=models.BooleanField(default=True),
        ),
    ]
