# Generated by Django 4.2.1 on 2023-06-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuraciones',
            old_name='linkfacebook',
            new_name='linklinkedin',
        ),
    ]
