# Generated by Django 4.2.1 on 2023-06-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_rename_linkfacebook_configuraciones_linklinkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciones',
            options={'verbose_name_plural': 'Configuraciones'},
        ),
    ]
