# Generated by Django 4.2.1 on 2023-07-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_remove_configuraciones_linkwhatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciones',
            name='correo_electronico',
        ),
    ]
