# Generated by Django 4.2.1 on 2023-07-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_remove_configuraciones_correo_electronico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuraciones',
            old_name='linkinstagram',
            new_name='link_instagram',
        ),
        migrations.RenameField(
            model_name='configuraciones',
            old_name='linklinkedin',
            new_name='link_linkedin',
        ),
        migrations.RenameField(
            model_name='configuraciones',
            old_name='telefono1',
            new_name='telefono_1',
        ),
        migrations.RenameField(
            model_name='configuraciones',
            old_name='telefono2',
            new_name='telefono_2',
        ),
    ]
