# Generated by Django 4.2.1 on 2023-07-05 00:37

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=51)),
                ('imagen', models.ImageField(blank=True, upload_to='productos')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('beneficios', ckeditor.fields.RichTextField()),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nombre', unique=True)),
                ('vigencia', models.BooleanField(default=True)),
            ],
        ),
    ]
