# Generated by Django 4.2.1 on 2023-05-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='static/resources')),
                ('descripcion', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=2000)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio_producto', to='producto.producto')),
            ],
        ),
    ]
