# Generated by Django 4.2.1 on 2023-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vigencia',
            field=models.BooleanField(default=True),
        ),
    ]
