# Generated by Django 4.1.7 on 2023-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0004_producto_vigencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, upload_to="productos"),
        ),
    ]
