# Generated by Django 4.2.1 on 2023-07-04 21:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioproducto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
